### ISSUE TITLE
Workflow is sending duplicate emails

### ISSUE THREAD

**Issue by danny-pl** [humanmade/altis-workflow#133]
We've set up workflows for Page Published and Post Published in Altis using the default set up, and set them to send emails to two addresses within Plan International. Each time a page or post is published we are receiving two identical emails. This is cluttering the notifications inbox
Steps to reproduce:
1.

We'd expect to only receive one email at the notification addresses when a post or page is published. 

![Post published workflow](https://user-images.githubusercontent.com/82154833/153247684-e53379b0-f1cf-4a64-a90e-1088304fbfdb.jpg)
![Page published workflow](https://user-images.githubusercontent.com/82154833/153247688-3e5ab50e-dc6d-4879-b2bd-1fd4e58c9899.JPG)
![Workflows window](https://user-images.githubusercontent.com/82154833/153247691-5e7ea53a-c708-4822-9625-b92f4ad65e4a.jpg)
I've added screenshots of the workflow window and then the set up of the pages and posts published workflows

Acceptance criteria:
One email whenever a page or post is published.
- [ ] ...

**Comment by roborourke** [comment]
Thanks the extra details @danny-pl, this has now been fixed in https://github.com/humanmade/Workflows/pull/163

Use `composer update altis/workflow --with-all-dependencies` to update.
