### ISSUE TITLE
Support config option for slack webhook & channel

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-workflow#15]
To take better advantage of the slack integration we should enable configuring it via `composer.json` along with the default target channel. We could also provide simple getter functions for these too that provide filters.

Lastly the built in workflows should be updated to post to slack too in the case that a webhook is provided.

**Comment by rmccue** [comment]
Should we have common Slack functionality as part of the Core module?

**Comment by jennybeaumont** [comment]
Closing as won't have
