### ISSUE TITLE
Duplicate "Copy to a new draft" link in WooCommerce

### ISSUE THREAD

**Issue by mattwatsoncodes** [humanmade/altis-workflow#158]
When viewing a product in altis, the "Copy to a new draft" link is duplicated within the publish meta box.

<img width="301" alt="Screenshot 2022-05-18 at 07 37 52" src="https://user-images.githubusercontent.com/2066205/168973691-68abeb98-0989-46e7-b0b0-4d206437116c.png">

If you remove the following line, the link will still be available, but will no longer be duplicated:

https://github.com/humanmade/altis-workflow/blob/1f488b79b47ce4ace8dc0279dd806a10d785f55a/inc/clone-amend/namespace.php#L28

<img width="301" alt="Screenshot 2022-05-18 at 07 40 57" src="https://user-images.githubusercontent.com/2066205/168974210-6743fb45-e110-4542-bf26-2014867fec50.png">

When the product is published the same issue occurs, however the "Rewrite and Republish" link is only availbale after the second link. 

<img width="302" alt="Screenshot 2022-05-18 at 07 49 00" src="https://user-images.githubusercontent.com/2066205/168975543-9aac6c2c-b666-4003-ab61-7ae192881b5e.png">

Removing the line of code shown above will not fix the issue, as the "Rewrite and Republish" link will no longer be shown. Only the "Copy to a new draft" link.

<img width="298" alt="Screenshot 2022-05-18 at 07 51 43" src="https://user-images.githubusercontent.com/2066205/168975986-969c1e87-497b-4940-a458-3dcffe1554c5.png">

**Comment by robindevitt** [comment]
> If you remove the following line, the link will still be available, but will no longer be duplicated:

@mattwatsoncodes removing that line, does it effect the other post types at all?

**Comment by mattwatsoncodes** [comment]
@robindevitt removing that line will remove the 'Rewrite and Republish` link when the post is published, so it's not really a viable solution. 

I suspect the filter `duplicate_post_enabled_post_types` is being used elsewhere to add in the 'product' CPT, which is why I highlighted that line :)

**Comment by roborourke** [comment]
Thanks @mattwatsoncodes - I think the implementation I would prefer is to preserve the Woo functionality for the product post type, so these would be the acceptance criteria:

- [ ] The `set_enabled_post_types` function in the `Altis\Workflow\Clone_Amend` namespace checks for whether Woo is active
- [ ] If Woo is active remove the product post type from the array of enabled post types before returning

**Comment by robindevitt** [comment]
Issue has been merged and closing out now.
