### ISSUE TITLE
WF Framework: Allow configurability of new statuses 

### ISSUE THREAD

**Issue by PriyaBhatia0210** [humanmade/altis-workflow#50]
## User Story:
As a Developer, I'd like to have a functionality that allows configurability of existing WP state machine so that I can quickly create custom statuses 

## Requirement:
1. A base plugin functionality that allows quick creation and definition of custom WP statuses in a standard way

## Acceptance Criteria:
Given: I am working on creating bespoke workflows for my business use case
When: I want to create a custom status
Then: I should be able to configure a new WP status quickly and program it for what it does in a standardized way
And: such that it is backward compatible and doesn't break the core operations

**Comment by rmccue** [comment]
Closing, we can reopen when we circle back to workflows.
