### ISSUE TITLE
WF Feature: Providing custom statuses Out of the Box

### ISSUE THREAD

**Issue by PriyaBhatia0210** [humanmade/altis-workflow#51]
## User Story:
As a platform provider, I'd like to provide a set of custom WP statuses built on our new Workflow framework solution so that I can establish a business utility value around it.

## Requirement:
1. The ability to showcase custom statuses to users that are not typically available with a standard WP install
2. More specifically the ability to showcase the following in addition to default WP statuses*:
- Back to Draft allows editing of a published post without affecting the original
- Under Review allows acceptance / rejection / comments on a post that has been assigned to a user
- Archive is storing away of old posts and pages and allowing retrieval
- Retrieved posts should be seen in 'All posts' page
- Trash is a deleted post

## Acceptance Criteria  
Given: I am demoing Altis to a prospect
When: I am showcasing our Workflow feature
Then: I should be able to showcase the creation of a custom workflow using custom statuses those are only available with OOTB to highlight what is possible with the Altis Workflow solution.  

*Will create separate issues for each when validated within the team.

**Comment by rmccue** [comment]
Closing, we can reopen when we circle back to workflows.
