### ISSUE TITLE
WF Framework: Allow status configurability of non-content object types

### ISSUE THREAD

**Issue by PriyaBhatia0210** [humanmade/altis-workflow#52]
Extension of #50 

No user story here; because we don't know the use case for Altis. However, something that can be contributed to the core.  

**Copying the discussion from the spike:**

**Chris:** Do we want the state machine to handle other types of statuses? E.g. comment status, user status, other object types, or do we want to restrict it to post types?

**Rob:** I think this would be a really great thing to keep in mind. I know that comments have a status column in their table, and users also have a status column (oddly the type is INT - possibly a throw back to the user level permissions system). What we're missing is a core column for term status to properly cover all core object types in WP. This might be one initial step we can contribute upstream to the core project as a step towards improving status management and workflows in WP core.

The other thing I'm not sure about here is whether statuses for other object types in WP have the same hooks or patterns associated with them that post statuses do. I imagine not. Again getting that to be handled consistently in core would be another step towards successfully layering on a system like the one we're proposing here.

So I imagine we focus on posts for now but for core contribution actions we could do the following:

- Adding a status column for terms
- Updating user status column to string / varchar (and any requisite core updates & handling for that)
- Adding the same status transition hooks for posts to users, comments and terms (where they don't currently exist)

**Ryan:** For now? No, let's keep the scope tight on post statuses. However, if it's possible for us to build in a little genericality so that we could do it in the future, let's keep it in mind.

**Comment by rmccue** [comment]
Closing, we can reopen when we circle back to workflows.
