### ISSUE TITLE
Add ability to save changes on a published post without publishing

### ISSUE THREAD

**Issue by PriyaBhatia0210** [humanmade/altis-workflow#57]
**User Story:**
As a user, I want to be able to edit an already published post so that I can make updates or amends
.
**Requirement:**
The ability to take a post back to draft state without affecting the original published post.

**Acceptance Criteria:**

_Scenario 1:_
Given: I am in the post editor screen of a published post
When: I go to the sidebar
Then: I should be able to see a 'Back to draft (?)' option below the 'Clone Post' option to take the post to an editable state for updates or amends   

_Scenario 2:_
Given: I click on the above 'Back to draft' button to take the post for a redraft
When: I check the original published post
Then: The original published post shall not be affected and shall be retained as is.

**Comment by jazzsequence** [comment]
This issue is superseded by #64
