### ISSUE TITLE
Add a 'Back to draft' option under each post

### ISSUE THREAD

**Issue by PriyaBhatia0210** [humanmade/altis-workflow#59]
**User Story:**
As a user, I want to take a published post to a redraft state from the list of all posts so that I dont have to go to the editor to redraft it.

**Requirement:**
The ability to take a published post to a redraft state from the list of all posts without having to go an extra step of going to the post editor to do the same. 

**Acceptance Criteria:**
_Scenario 1:_
Given: I am in the All Posts page of the admin
When: I hover over a post title in the list of All posts
Then: I should see an option 'Back to draft' to take the post to a redraft state after the 'Clone' option. 

_Scenario 2:_
Given: I am in the All Posts page of the admin
When: I click on the 'Back to draft' of a published post
Then: I should be taken to the post editor of the published post which doesnt affect the original post.

**Comment by roborourke** [comment]
We're not 100% sure how the functionality should work yet so closing this pending the spike here https://github.com/humanmade/altis-workflow/issues/56
