### ISSUE TITLE
The 'Publish' button to read 'Republish' in case of a post that is being edited in 'Back to Draft' mode

### ISSUE THREAD

**Issue by PriyaBhatia0210** [humanmade/altis-workflow#60]
**User Story:**
As a user, I want to see a republish button in place of a publish button for a post taken to redraft so that I know I am editing a redraft version of the post and that the original post is intact.

**Requirement:**
- The ability to republish changes / updates to an already published post 
- The ability to distinguish between a regular and a redraft of a post

_Acceptance Criteria:_

_Scenario 1:_ 
Given: I am the post editor of the redraft version of a published post
When: I want to publish the changes to the post 
Then: The 'Publish' button should read 'Republish'

_Scenario 2:_
Given: I want to republish changes to an already published post
When: I click on the above 'Republish' button
Then: A warning message should read that "This operation will replace the original post. Are you sure?"

**Comment by roborourke** [comment]
The requirements in this issue will be handled differently, as it stands it's not really an actionable task.
