### ISSUE TITLE
TBD: What should 'Switch to draft' read as in case of a 'Back to draft' button option?

### ISSUE THREAD

**Issue by PriyaBhatia0210** [humanmade/altis-workflow#61]
Right now there is a 'Switch to draft' option for a post that takes a post offline and un-publishes it.
With the new functionality with 'Back to draft' this can become confusing. 

We need to think of ways these can be delineated. 

One way is calling 'Switch to draft' as 'Un-publish post' which is what it essentially does.

**Comment by roborourke** [comment]
We will answer this question in this spike https://github.com/humanmade/altis-workflow/issues/56
