### ISSUE TITLE
Allow updates to published posts

### ISSUE THREAD

**Issue by jazzsequence** [humanmade/altis-workflow#64]
**User Story:**
As a user, I want to be able to edit an already published post so that I can make updates or amends.

**Requirement:**
The ability to edit and revise a post without affecting the original published post.

Per #56 we have decided to use [Yoast/duplicate-post](https://github.com/Yoast/duplicate-post) for this functionality. 

**Acceptance Criteria**
- [x] Yoast/duplicate-post is published to Packagist.org
- [x] Update `composer.json` to add `yoast/duplicate-post` as a dependency of the module
- [x] Add integration and config code to load in the plugin
- [x] Remove `humanmade/post-cloner` from module (functionality is duplicated by Yoast/duplicate-post)
- [x] User documentation
- [x] Hide the settings page & allow (some) settings to be configured from the config
- ~Remove "New Draft" from quick action row~ Microcopy to be handled in #66

**Comment by jazzsequence** [comment]
They've added it: https://packagist.org/packages/yoast/duplicate-post

**Comment by roborourke** [comment]
You commented about the number of extra links this plugin adds into what shows up on hover in the post lists taking up a lot of space, what I'm wondering is what the need or use case for both the "New Draft" and "Clone / Duplicate" options are. They're very similar, and from the description in the docs the only difference is that one can be detached from it's original post. Do we think there's value in all the options or should we simplify it a bit and remove the "New Draft" option?

**Comment by rmccue** [comment]
Yeah, I'm also unclear on what the distinction is with those tbh. I'll ask!

**Comment by jazzsequence** [comment]
For posterity, per the slack convo: "New Draft" and "Clone" are the same feature. The only difference between the two is that "New Draft" immediately takes you to the edit screen (you can detach both from the original). Since we're using this plugin to replace our Post Cloner plugin, and "Clone" was already part of the quick action links, I would agree and opt for removing the "New Draft" option.

**Comment by rmccue** [comment]
Discussion about microcopy split to https://github.com/humanmade/altis-workflow/issues/66

> Do you have thoughts about whether this should go in the CMS module (where post cloner was) or the Workflow module (where the feature was scoped)?

Workflow IMO.

**Comment by roborourke** [comment]
Closed in #65

Any further work should be done through new issues.
