### ISSUE TITLE
Highlight that you are editing a cloned post

### ISSUE THREAD

**Issue by jazzsequence** [humanmade/altis-workflow#68]
@PriyaBhatia0210 commented on [Fri Apr 16 2021](https://github.com/humanmade/product-dev/issues/707)

I am not sure whether this is valuable.

However, when I working in a cloned post there is no way of knowing whether it is the clone or the original post I am working in unless I go to the dashboard .

I was looking for this microcopy or tag because the preview of the cloned post is breaking. Hence, I had to go to the original post to make the edits and view again. 

Acceptance Criteria:
- [ ] Given I am in the editor of a cloned post
- [ ] Then there could be a microcopy in the sidebar that tells me that I am working in a clone of a 'XX' post  

---

@rmccue commented on [Thu Jun 03 2021](https://github.com/humanmade/product-dev/issues/707#issuecomment-854032363)

This is still true for the Duplicate Post plugin we're switching to, however there are other UI changes in place, including a (dismissable) banner and microcopy when clicking Publish.

However, unsure if any indication appears in the sidebar permanently. tbd.

---

@jazzsequence commented on [Thu Jun 03 2021](https://github.com/humanmade/product-dev/issues/707#issuecomment-854032980)

I will doublecheck this functionality and report back.

**Comment by jazzsequence** [comment]
When you click to "Rewrite & Republish" a post, a banner appears at the top of the screen and the "Publish" button becomes "Republish".

![Screen Shot 2021-06-03 at 11 42 38 AM](https://user-images.githubusercontent.com/991511/120689064-ef8f9100-c460-11eb-89d6-8752c53c9737.png)

In addition to that, there's a sidebar panel that indicates what the original post was:

![Screen Shot 2021-06-03 at 11 44 17 AM](https://user-images.githubusercontent.com/991511/120689164-0f26b980-c461-11eb-9920-9832b3e719df.png)

The banner is dismissable and there is no permanent indication in the sidebar (other than the Duplicate Post panel) that informs the user that this is a rewritten, however when the "Republish" button is clicked, a "Republish Date" can be specified and when the post is successfully published (if it is republished immediately) an updated banner appears that says that it has replaced/updated the original post.

![Screen Shot 2021-06-03 at 11 46 22 AM](https://user-images.githubusercontent.com/991511/120689547-793f5e80-c461-11eb-977d-ca5ce8e89282.png)

![Screen Shot 2021-06-03 at 11 45 50 AM](https://user-images.githubusercontent.com/991511/120689583-81979980-c461-11eb-8f42-589c2c71dde6.png)

**Comment by jazzsequence** [comment]
**Clone**

For a "Cloned" post, there is no visual indication that the post you are editing is a duplicate other than the "Rewrite & Replace" option being removed from the sidebar (you can't republish a draft -- although you can create a New Draft) and the Duplicate Post panel at the bottom including a "Delete reference to original item" option.

![Screen Shot 2021-06-03 at 11 49 26 AM](https://user-images.githubusercontent.com/991511/120690625-b2c49980-c462-11eb-9a3c-d621158e3974.png)

**Note:** This feature is functionally identical to the "New Draft" function and we're likely removing it in favor of "New Draft" #66

**Comment by rmccue** [comment]
It sounds like we have plenty of notices already which distinguish this as a duplicated/rewritten/whatever post, although the banner is dismissable, and the sidebar widget can be a bit hidden.

Marking as a could have, because we could iterate and improve on it.

**Comment by rmccue** [comment]
> Note: It appears that our custom post-publish panel for workflows overrides the one that the Duplicate Post plugin adds with the additional microcopy:

Split to #69.

**Comment by rmccue** [comment]
Split the fixing the publication checklist to #71.

Apart from that, the existing indicators are already enough to indicate you're editing a rewritten version (i.e. the main button shows "Republish")
