### ISSUE TITLE
Display "are you ready to republish" copy and compare button on republished posts

### ISSUE THREAD

**Issue by rmccue** [humanmade/altis-workflow#71]
Our publication checklist hides the default button and text when clicking the "Publish" button, so that our overridden button is displayed instead. We should show the Duplicate Post copy and button on posts which are being rewritten.

* [x] As a content author, when I'm on a rewritten post and I click Republish, I should see the publication checklist
* [x] As a content author, when I'm on a rewritten post and I click Republish, I should see the "are you ready to republish" copy and "save changes and compare" button
* [x] As a content author, when I'm on a rewritten post and I click Republish, I should see a "Republish" button instead of "Publish"
* [x] As a content author, when I'm on a rewritten post and I click Republish, the (second) Republish button should be disabled if any mandatory publication checks fail

Potential rabbitholes here with the research, especially integration of the two buttons, and what has changed since the original motivation for the publication checklist's hack. Also, how easy is it to actually use the stuff from Duplicate Post?

Gutenberg may now have a thing called isPostPublishable which allows us to remove our hack of replacing the button.

**Comment by roborourke** [comment]
Seems one way to do it could be to trigger some small change to the post status once the publish panel comes up but no idea what events or hooks there are. Seems nothing has really changed unfortunately.

This I think is the `core/editor` store selector value we'd want to override:

https://github.com/WordPress/gutenberg/blob/9580b45e6e18dd06076af9f7e1ea66babee22bf5/packages/editor/src/store/selectors.js#L512-L531

Maybe we could write a data registry plugin for the `core/editor` store that overwrites that selector with one that checks if the publication checklist options have passed too.

https://developer.wordpress.org/block-editor/reference-guides/packages/packages-data/#use

**Comment by roborourke** [comment]
Found that the `lockPostSaving()`,`unlockPostSaving()` methods now take a string for named locks, so we can use that enable or disable the publish button. They still allow for changes to a draft to be saved.

- https://developer.wordpress.org/block-editor/reference-guides/data/data-core-editor/#lockPostSaving
- https://developer.wordpress.org/block-editor/reference-guides/data/data-core-editor/#unlockPostSaving

**Comment by roborourke** [comment]
Fixed by https://github.com/humanmade/publication-checklist/pull/19
